remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
repository: vadimhungry/vadimhungry.github.io
logo: assets/img/logo.jpg
url: https://vadimhungry.github.io
author: "vadim"
description: "personal homepage"

